package com.example.unitrip.domain.notification.entity;

public enum NotificationType {
    APPOINTMENT_REMINDER,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REQUEST,
    APPOINTMENT_CHANGE_REQUEST,
    BOOKING_CONFIRMED,
    NEW_MESSAGE,
    UNREAD_MESSAGES,
    PAYMENT_PENDING,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    EVENT_STARTED,
    EVENT_CLOSING_SOON,
    HOT_THIS_WEEK,
    REFERRAL_EVENT,
    REVIEW_REQUEST
}
