# -*- coding: utf-8 -*-
"""ART NARA 앱 기획 DB 원본 데이터.

화면 하나가 dict 하나다. Notion DB 속성과 페이지 본문이 모두 여기서 나온다.
Figma 가 없는 화면(웹뷰·셸 등)은 node 를 빈 값으로 둔다 — URL 도 비워진다.

Figma 파일:
  DESIGN  = 26.07.29 리비전 (실제 디자인)
  WIRE    = Manyfast 와이어프레임 (디자인 없이 구현한 화면의 사후 와이어프레임)
"""

DESIGN = 'ZqY7Mo7424n3gMp5kZJ4AZ'
WIRE = 'PEgRT86N0VTa1bXgTruP4S'

SCREENS = [
    # ---------- 00 진입 ----------
    dict(
        id='AN-ENT-010', name='스플래시 · 온보딩', group='00_진입',
        file=DESIGN, node='1:722', code='splash_onboarding_screen.dart',
        summary='앱 첫 화면. 저장된 토큰으로 자동 로그인을 시도하고, 실패하면 온보딩을 보여준다.',
        scenario='앱을 켜면 브랜드 화면이 뜨고, 이전에 로그인한 적이 있으면 곧바로 메인(또는 미완료 단계)으로 들어간다. 처음이면 온보딩 4장을 넘긴 뒤 시작하기를 누른다.',
        layout=['배경 이미지 + ART·NARA 워드마크', '온보딩 페이지 인디케이터(4)', '시작하기 버튼'],
        features=[
            '자동 로그인: refresh token 으로 토큰 재발급 → 프로필 완료면 메인, 미완료면 역할 선택',
            '401(계정 없음/로그아웃됨)이면 저장 토큰을 폐기하고 온보딩 유지',
            '네트워크 오류는 토큰을 지우지 않는다(일시 장애로 로그아웃되면 안 된다)',
            '로그인 신원이 생긴 뒤 FCM 기기 토큰 등록',
        ],
        done=['재실행 시 재로그인 없이 진입한다', 'DB 초기화 등으로 계정이 사라지면 크래시 없이 온보딩으로 복귀한다'],
        notes=['자동 로그인 성공/실패 로그: [AuthAPI] 자동 로그인 성공|실패'],
        deps='→ AN-ENT-020(로그인), → AN-ENT-040(역할 선택), → AN-HOME-010(메인)',
    ),
    dict(
        id='AN-ENT-020', name='로그인', group='00_진입',
        file='', node='', code='login_screen.dart',
        summary='카카오 · 네이버 소셜 로그인. 서버가 OAuth 신원을 검증하고 앱 JWT 를 발급한다.',
        scenario='시작하기를 누르면 카카오/네이버 버튼이 있는 화면이 나온다. 하나를 고르면 각 제공자 화면으로 넘어가고, 승인하면 신규는 역할 선택으로, 기존 회원은 메인으로 들어간다.',
        layout=['워드마크 + 안내 문구', '카카오로 시작하기(노랑)', '네이버로 시작하기(N 글리프 네이버 그린)'],
        features=[
            '카카오: SDK 로 액세스 토큰 획득 → POST /auth/login',
            '네이버: WebView 로 인가 코드만 받아 POST /auth/naver/code (시크릿은 서버에만)',
            '신규 여부(isNewUser)·프로필 완료 여부로 다음 화면 분기',
            '실패·취소는 스낵바로 알리고 화면 유지',
        ],
        done=['두 제공자 모두 로그인되고 JWT 가 저장된다', '취소해도 앱이 정상 동작한다'],
        notes=['버튼 아이콘은 로컬 글리프 — 네트워크 이미지는 빈 칸으로 렌더되어 교체했다',
               'Figma 디자인 없음(스플래시 프레임에 포함되지 않은 별도 화면)'],
        deps='← AN-ENT-010, → AN-ENT-030(네이버 웹뷰), → AN-ENT-040',
    ),
    dict(
        id='AN-ENT-030', name='네이버 로그인 (WebView)', group='00_진입',
        file='', node='', code='naver_login_screen.dart',
        summary='네이버 동의 화면을 앱 WebView 로 띄우고 인가 코드만 가로챈다.',
        scenario='네이버로 시작하기를 누르면 네이버 로그인 폼이 앱 안에서 열린다. 로그인·동의를 마치면 자동으로 창이 닫히고 로그인이 완료된다.',
        layout=['상단 바(닫기 ✕ · "네이버 로그인")', 'WebView', '로딩 인디케이터'],
        features=[
            'GET /auth/naver/config 로 동의 화면 주소 수신(state 는 앱이 생성)',
            'NavigationDelegate 가 redirect_uri 이동을 가로채 인가 코드 추출',
            'state 불일치면 코드를 버린다(요청 위조 방지)',
            '페이지 로드·웹 콘솔·리소스 오류 로깅(쿼리스트링은 잘라 코드 유출 방지)',
        ],
        done=['동의 완료 시 서버 코드 교환까지 이어져 JWT 가 발급된다'],
        notes=['SDK 를 쓰지 않는 이유: 커스텀탭 intent:// 콜백이 전달되지 않는 환경이 있었다',
               '우리 WebView 는 어떤 URL 이든 가로채므로 앱 스킴 콜백도 사용 가능'],
        deps='← AN-ENT-020',
    ),
    dict(
        id='AN-ENT-040', name='역할 선택', group='00_진입',
        file=WIRE, node='27:2', code='role_selection_screen.dart',
        summary='작가 / 컬렉터 중 하나를 고른다. 화면 구성이 역할에 따라 갈린다.',
        scenario='가입 직후 "어떤 회원으로 시작할까요?" 화면에서 작가 또는 컬렉터를 고르면 해당 프로필 설정으로 넘어간다.',
        layout=['제목 + 부제', '작가 카드(내 작품을 등록하고 판매)', '컬렉터 카드(작품을 발견하고 소장)'],
        features=['선택한 역할이 프로필 설정 화면의 항목 구성을 바꾼다', '가입 후에도 마이페이지에서 전환 가능'],
        done=['선택에 따라 작가/컬렉터 프로필 설정이 열린다'],
        notes=['백엔드 userType: 작가=KOREAN_STUDENT, 컬렉터=FOREIGN_TOURIST (여행 앱 시절 enum 이름 잔재)'],
        deps='← AN-ENT-010/020, → AN-ENT-050',
    ),
    dict(
        id='AN-ENT-050', name='프로필 설정', group='00_진입',
        file=WIRE, node='27:17', code='profile_setup_screen.dart',
        summary='활동명·나이·지역·소개·장르를 입력해 가입을 완료한다.',
        scenario='역할을 고르면 프로필 입력 화면이 나온다. 활동명과 지역을 채우고 관심 장르를 고른 뒤 시작하기를 누르면 메인으로 들어간다.',
        layout=['프로필 이미지', '활동명(닉네임) · 이름(선택) · 나이', '활동 지역(시·도 선택)', '작가 소개 / 취향 소개', '장르 칩(회화·조각·디지털·사진·일러스트·공예)', 'ART NARA 시작하기'],
        features=[
            'POST /api/users 로 프로필 저장 → profileCompleted=true',
            '필수값 미입력 시 스낵바로 안내(예: 활동 지역을 선택해주세요)',
            '역할에 따라 문구가 작가/컬렉터로 바뀐다',
        ],
        done=['저장 후 메인으로 진입하고 마이페이지에 값이 반영된다'],
        notes=['활동명은 작품·주문·정산이 참조하는 키다 — 개명 시 이력이 끊기는 한계가 있다(알려진 한계 참고)'],
        deps='← AN-ENT-040, → AN-HOME-010',
    ),
    dict(
        id='AN-ENT-060', name='메인 셸 (하단 6탭)', group='00_진입',
        file='', node='', code='main_screen.dart',
        summary='홈·판매·지도·제작의뢰·알림·마이페이지 탭을 담는 셸. 헤더와 서랍을 제공한다.',
        scenario='로그인 후 들어오는 기본 화면. 하단 탭으로 이동하고, 좌측 상단 햄버거로 작품 문의(채팅)와 설정에 접근한다.',
        layout=['헤더(햄버거 · 화면 제목 · 알림 벨+배지)', '탭 본문', '하단 내비 6탭'],
        features=['탭 상태 보관', '알림 미읽음 배지', '햄버거 서랍: 작품 문의 · 설정(로그아웃)'],
        done=['6탭 이동과 서랍 진입이 정상 동작한다'],
        notes=['디자인 리비전에서 채팅 탭이 빠지면서 작품 문의를 서랍으로 옮겼다', '화면 제목은 헤더에서만 그린다(본문 중복 금지)'],
        deps='→ 전 탭',
    ),

    # ---------- 10 홈 ----------
    dict(
        id='AN-HOME-010', name='홈 피드 (둘러보기)', group='10_홈',
        file=DESIGN, node='1:549', code='art_home_feed_screen.dart',
        summary='추천 작품 · 마감 임박 경매 · 주목할 작가를 한 화면에 모은 탐색 피드.',
        scenario='앱에 들어오면 추천 작품 그리드가 보이고, 아래로 내리면 진행 중인 경매와 작가 목록이 나온다. 검색어나 카테고리 칩으로 걸러 볼 수 있다.',
        layout=['검색바 + 필터', '카테고리 칩(추천·회화·조각·디지털·사진·일러스트)', '추천 작품 2열 그리드(하트)', '마감 임박 경매(현재가·남은 시간)', '주목할 작가(문의하기)'],
        features=[
            'GET /api/feed/home (검색어·카테고리 필터)',
            '작품 카드: 판매 완료 딤 + 칩, 예약중 칩(구분 표시)',
            '하트 토글(POST /api/artworks/{id}/like) — 로그인 사용자 상태 반영',
            '경매 카드 남은 시간 로컬 카운트다운(서버 폴링 없음)',
            '섹션당 20건 상한 + 더보기',
        ],
        done=['필터가 서버 결과와 일치한다', '판매완료·예약중이 카드에서 구분된다'],
        notes=['응답 키는 recommended / auctions / artists (artworks 아님)'],
        deps='→ AN-HOME-020(더보기), → AN-HOME-030(작품 상세), → AN-HOME-040(작가), → AN-CHAT-020(문의)',
    ),
    dict(
        id='AN-HOME-020', name='작품 목록 (더보기)', group='10_홈',
        file=WIRE, node='28:94', code='artwork_list_screen.dart',
        summary='피드 섹션의 전체 목록. 최신순 무한 스크롤.',
        scenario='추천 작품 옆 더보기를 누르면 전체 목록이 열리고, 아래로 내리면 계속 불러온다.',
        layout=['상단 바', '작품 카드 목록(썸네일·제목·작가·가격)'],
        features=['GET /api/artworks?page=&size=&category= (size 1~50 클램프)', '무한 스크롤 페이징', '판매완료/예약중 오버레이'],
        done=['스크롤로 다음 페이지가 이어 붙는다'],
        notes=['Spring Page 응답이라 목록 키가 content 다(피드의 artworks 와 다름)'],
        deps='← AN-HOME-010, → AN-HOME-030',
    ),
    dict(
        id='AN-HOME-030', name='작품 상세', group='10_홈',
        file=WIRE, node='22:3', code='artwork_detail_screen.dart',
        summary='작품 정보 · 작가 카드 · 예약(또는 입찰) 액션을 담은 상세 화면.',
        scenario='작품을 누르면 이미지와 설명, 재료·크기·소유권 인증 안내가 나온다. 즉시 판매면 예약하기, 경매면 입찰 입력이 하단에 뜬다. 작가에게 바로 문의할 수도 있다.',
        layout=['헤더(제목)', '작품 이미지', '제목·작가·연도·가격(경매면 현재가+남은 시간)', '작품 설명', '사양 표(재료·크기·소유권 인증)', '작가 카드 + 문의하기', '하단 액션 바'],
        features=[
            'GET /api/artworks/{id}',
            '즉시 판매: 예약하기 → POST /api/orders (결제 아님)',
            '경매: 입찰(POST bids), 최소 증분 미달이면 거절',
            '진행 중 경매만 /topic/auction/{id} 구독 → 수신 시 상세 재조회',
            '상태별 하단 바: 판매 완료 / 예약 중 / 입찰 / 낙찰가로 예약',
        ],
        done=['예약 시 작품이 잠기고 다른 사람은 예약할 수 없다', '남의 입찰이 화면 조작 없이 반영된다'],
        notes=['낙찰 여부는 서버가 wonByViewer 로 계산 — 클라이언트가 이름 비교하지 않는다'],
        deps='← AN-HOME-010/020, → AN-TRADE-020(주문 내역), → AN-CHAT-020',
    ),
    dict(
        id='AN-HOME-040', name='작가 포트폴리오', group='10_홈',
        file=DESIGN, node='1:278', code='artist_portfolio_screen.dart',
        summary='작가 소개 · 작품 목록 · 리뷰(평점)를 보여주는 프로필 화면.',
        scenario='작가 이름을 누르면 그 작가의 소개와 등록 작품, 구매자 리뷰를 볼 수 있다. 여기서도 바로 문의할 수 있다.',
        layout=['작가 프로필(이름·소개·평점·판매 수)', '작품 탭 / 리뷰 탭', '문의하기'],
        features=['GET /api/artists/{활동명}', 'GET /api/artists/{활동명}/reviews (최신 100건 + 평균)', '작품 탭에서 상세로 이동'],
        done=['평점·리뷰 수가 실제 집계와 일치한다'],
        notes=['작가 식별이 활동명 문자열 기준이다'],
        deps='← AN-HOME-010, AN-HOME-030',
    ),

    # ---------- 20 거래 ----------
    dict(
        id='AN-TRADE-010', name='결제 (예약 건 결제)', group='20_거래',
        file=WIRE, node='22:4', code='checkout_screen.dart',
        summary='양쪽 수령 확인이 끝난 예약을 결제한다. 결제 확정 시 소유권이 발급된다.',
        scenario='만나서 작품을 주고받고 양쪽이 확인하면 주문 내역에 결제하기가 열린다. 누르면 금액과 결제 수단을 확인하고 결제한다. 실 PG 가 켜져 있으면 토스 결제창이 뜬다.',
        layout=['상단 바(주문/결제)', '작품 요약 카드(수령 확인 완료 · 결제만 남았어요)', '결제 수단 선택(카드·카카오페이·네이버페이·토스페이)', '금액 요약', '결제하기'],
        features=[
            'POST /api/orders/{id}/pay (구매자만, 양쪽 확인 후에만)',
            '실 PG 사용 시 TossPaymentScreen 경유 → paymentKey 를 서버가 승인',
            '결제 완료 다이얼로그 + 소유권 인증서 번호 안내',
        ],
        done=['결제 후 작품이 판매 완료로 잠기고 인증서가 발급된다', '확인 전 결제는 서버가 400 으로 막는다'],
        notes=['이 화면은 주문을 만들지 않는다 — 이미 있는 예약(orderId)을 결제한다'],
        deps='← AN-TRADE-020, → AN-TRADE-011(토스), → AN-OWN-020(인증서)',
    ),
    dict(
        id='AN-TRADE-011', name='토스 결제창 (WebView)', group='20_거래',
        file='', node='', code='toss_payment_screen.dart',
        summary='토스페이먼츠 결제위젯을 WebView 로 띄우고 승인 결과를 가로챈다.',
        scenario='결제하기를 누르면 토스 결제창이 열린다. 결제수단을 고르고 인증을 마치면 창이 닫히며 결제가 완료된다.',
        layout=['상단 바(결제 · 닫기)', '토스 결제위젯 WebView'],
        features=[
            '에셋 HTML 을 문자열로 읽어 설정을 주입하고 baseUrl 을 성공 URL 과 같은 오리진으로 로드',
            'successUrl/failUrl 이동을 가로채 paymentKey 획득',
            'http 가 아닌 스킴(카드사 앱)은 외부 앱 실행 → 실패 시 마켓으로 폴백',
        ],
        done=['샌드박스 결제가 승인되고 서버 confirm 까지 이어진다'],
        notes=['loadFlutterAsset 에 쿼리스트링을 붙이면 에셋을 못 찾는다', '에뮬레이터엔 카드사 앱이 없어 퀵계좌이체로 검증'],
        deps='← AN-TRADE-010',
    ),
    dict(
        id='AN-TRADE-020', name='주문 내역 (구매자)', group='20_거래',
        file=WIRE, node='28:42', code='order_history_screen.dart',
        summary='내가 예약·구매한 거래 목록. 직거래 단계에 따라 버튼이 바뀐다.',
        scenario='마이페이지 > 주문 내역에서 진행 중인 거래를 본다. 작품을 받았으면 받았어요를 누르고, 양쪽 확인이 끝나면 결제하기가 열린다. 결제 후에는 리뷰를 쓸 수 있다.',
        layout=['상단 바(주문 내역)', '거래 카드: 제목·작가·금액·단계 배지', '단계 안내 문구', '액션(예약 취소 / 받았어요 / 결제하기 / 리뷰 쓰기)'],
        features=[
            'GET /api/orders (JWT 신원으로 스코프)',
            'POST /api/orders/{id}/handover (받았어요)',
            'POST /api/orders/{id}/cancel (예약 취소)',
            '결제 완료 건만 리뷰 작성 가능(환불되면 숨김)',
        ],
        done=['단계 배지가 예약 중 → 수령 확인 중 → 결제 대기 → 거래 완료로 진행한다'],
        notes=['환불 건은 "환불되어 디지털 소유권이 회수되었습니다" 로 표시'],
        deps='← AN-MY-010, → AN-TRADE-010',
    ),
    dict(
        id='AN-TRADE-030', name='내 작품 거래 (판매자)', group='20_거래',
        file='', node='', code='order_history_screen.dart (selling=true)',
        summary='내 작품에 걸린 예약·거래 목록. 판매자가 전달을 확인하는 화면.',
        scenario='작가는 마이페이지 > 내 작품 거래에서 누가 예약했는지 보고, 만나서 전달한 뒤 전달했어요를 누른다.',
        layout=['상단 바(내 작품 거래)', '거래 카드(구매자·금액·단계)', '액션(예약 취소 / 전달했어요)'],
        features=['GET /api/orders/selling (활동명 기준)', 'POST /api/orders/{id}/handover (전달했어요)'],
        done=['판매자 확인 후 배지가 수령 확인 중으로 바뀐다'],
        notes=['주문 내역과 같은 화면을 selling 플래그로 재사용 — 버튼 문구만 판매자 시점으로 바뀐다',
               'Figma 없음(직거래 도입과 함께 신설)'],
        deps='← AN-MY-010',
    ),

    # ---------- 30 판매 ----------
    dict(
        id='AN-SELL-010', name='작품 판매 등록', group='30_판매',
        file=DESIGN, node='1:654', code='sell_screen.dart',
        summary='4스텝 위저드로 작품을 등록한다(즉시 판매 / 경매).',
        scenario='판매 탭에서 작품 정보와 사진, 상세 사양, 가격을 차례로 입력하면 등록이 완료되고 피드에 바로 노출된다.',
        layout=['스텝 인디케이터(작품 정보 · 상세 정보 · 가격 설정 · 등록 완료)', '단계별 입력 폼', '이전/다음'],
        features=[
            'POST /api/sales (판매자는 JWT 신원)',
            '이미지 업로드 POST /api/images',
            '경매 설정(시작가·마감일) — 마감은 다음 날 이후만',
            '필수값 검증 스낵바',
        ],
        done=['등록 즉시 공개 피드·지도에 노출되고 내 판매 작품에만 내 것이 보인다'],
        notes=['디자인은 5스텝(배송 정보 포함)이지만 배송이 없어 4스텝으로 운영',
               '경매여도 buyNowPrice 필수(없으면 SALE_400_PRICE)'],
        deps='→ AN-HOME-010, AN-MAP-010',
    ),
    dict(
        id='AN-SELL-020', name='판매 정산', group='30_판매',
        file='', node='', code='settlement_screen.dart',
        summary='작가의 판매 합계·수수료·정산 예정액과 건별 내역.',
        scenario='작가가 마이페이지 > 판매 정산에서 얼마 팔렸고 얼마 받게 되는지 확인한다.',
        layout=['요약 카드(판매 합계 · 수수료 · 정산 예정액)', '이번 달 판매', '건별 내역(작품·구매자·금액·수수료)'],
        features=['GET /api/settlements (활동명 기준)', '결제 완료 건만 집계 — 예약·환불 건은 제외(환불은 이력에만)'],
        done=['정산 예정액 = 판매 합계 − 수수료'],
        notes=['수수료 10% 는 사업계획서에 요율이 없어 정한 기본값(SettlementService.FEE_RATE)',
               '작가일 때만 메뉴 노출. Figma 없음'],
        deps='← AN-MY-010',
    ),

    # ---------- 40 의뢰 ----------
    dict(
        id='AN-REQ-010', name='제작 의뢰 신청 · 목록', group='40_의뢰',
        file=DESIGN, node='1:349', code='commission_screen.dart',
        summary='원하는 작품을 의뢰하면 작가들이 더 낮은 금액을 제안하는 역경매.',
        scenario='컬렉터가 내용·예산·희망일과 카테고리를 적어 의뢰하면 해당 장르 작가들에게 알림이 간다. 작가는 목록에서 의뢰를 보고 제안 금액을 적어 보낸다.',
        layout=['의뢰 세부 내용 · 참고 이미지', '예산 · 희망 마감일', '선호 카테고리 칩(복수)', '안내 박스', '의뢰 요청하기', '의뢰 목록(상태 배지 · 제안 목록 · 제안하기)'],
        features=[
            'POST /api/commissions {title, description, category, budget, desiredDate, referenceImageUrl}',
            '등록 시 선택 카테고리 작가들에게 알림 발송',
            'POST /api/commissions/{id}/offers — 현재 최저가보다 낮아야 등록(위반 422)',
            '제안 도착 시 의뢰인에게 알림',
        ],
        done=['예산 초과 제안은 거절되고 정상 제안은 최저가로 갱신된다'],
        notes=['필드명은 budget (budgetMin/Max 아님)'],
        deps='→ AN-NOTI-010',
    ),

    # ---------- 50 지도 ----------
    dict(
        id='AN-MAP-010', name='지도 (집 주변 작품)', group='50_지도',
        file=WIRE, node='27:41', code='map_screen.dart',
        summary='내 주변 작품을 지도 핀으로 보여준다. SDK 실패 시 거리순 목록으로 폴백.',
        scenario='지도 탭을 열면 주변 작품이 핀으로 찍힌다. 핀을 누르면 하단에 작품 카드가 뜨고, 카드를 누르면 상세로 간다.',
        layout=['카카오맵', '브랜드 색 핀', '선택 작품 카드', '확대/축소 버튼', '(폴백) 거리순 목록'],
        features=[
            'GET /api/artworks/nearby?latitude=&longitude=',
            '핀 탭 → 작품 카드 → 상세',
            '지도 SDK 초기화 실패 시 같은 데이터로 목록 표시',
        ],
        done=['새로 등록한 작품이 지도/목록에 반영된다'],
        notes=['카카오맵 네이티브는 arm 전용 — x86_64 프로세스면 목록 폴백(Abi.current() 로 판단)',
               '좌표가 없는 작품은 id 기준 황금각으로 흩뿌려 겹치지 않게 한다',
               '핀치 줌이 불가한 환경을 위해 줌 버튼 제공'],
        deps='→ AN-HOME-030',
    ),

    # ---------- 60 소유권 ----------
    dict(
        id='AN-OWN-010', name='소유권 인증 · 디지털 소유권', group='60_소유권',
        file='', node='', code='certificate_screen.dart',
        summary='내가 보유한 디지털 소유권 목록과 QR 스캔 진입.',
        scenario='마이페이지에서 들어가면 내 소유권 목록이 보이고, QR 스캔으로 다른 작품의 소유권도 확인할 수 있다.',
        layout=['QR 스캔 진입', '내 소유권 목록(인증서 번호·작품·작가·취득일)'],
        features=['GET /api/certificates (JWT 신원 스코프, 환불 회수 건 제외)', 'QR 스캔 화면으로 이동'],
        done=['남의 소유권이 섞이지 않는다'],
        notes=['Figma 없음(인증서 카드 디자인은 상세 화면에 있음)'],
        deps='← AN-MY-010, → AN-OWN-020, AN-OWN-030',
    ),
    dict(
        id='AN-OWN-020', name='소유권 인증서 상세', group='60_소유권',
        file=DESIGN, node='1:737', code='certificate_detail_screen.dart',
        summary='골드 프레임 인증서 카드. 작품 사양과 소유자·고유 번호가 새겨진다.',
        scenario='소유권을 누르면 인증서 카드가 뜬다. 작품명·작가·제작 연도·크기·재료와 소유자, 인증 번호를 확인할 수 있다.',
        layout=['골드 프레임 카드', '─ 소유권 인증서 ─ 제목', '작품 제목·작가', '제작 연도·크기·재료', '소유자', '고유 인증 ID'],
        features=['결제 시점의 작품 사양을 복사해 보관(이후 작품 정보가 바뀌어도 인증서는 그대로)'],
        done=['결제 즉시 발급되고 마이페이지에서 조회된다'],
        notes=['씰 표기는 AN', '두 번째 프레임(1:806)은 변형 레이아웃'],
        deps='← AN-OWN-010, AN-TRADE-010',
    ),
    dict(
        id='AN-OWN-030', name='QR 소유권 인증 스캔', group='60_소유권',
        file=WIRE, node='28:78', code='qr_scan_screen.dart',
        summary='QR 을 찍거나 코드를 직접 입력해 소유권 이력을 확인한다. 비로그인도 가능.',
        scenario='작품에 붙은 QR 을 찍으면 누가 소유자인지, 유효한 인증서인지 바로 나온다.',
        layout=['카메라 프리뷰', '수동 입력 필드', '결과 카드'],
        features=[
            'POST /api/certificates/scan {qrCode} — 유일한 메서드 무관 공개 API',
            '유효: 소유자·작품 사양 표시 / 환불 건: verified=false + 무효 안내',
        ],
        done=['누구나(비로그인) 확인할 수 있다', '환불된 인증서는 무효로 표시된다'],
        notes=['QR 값은 ARTNARA-QR-{끝자리} — 인증서 번호(ARTNARA-2026-xxx)와 다른 값이다'],
        deps='← AN-OWN-010',
    ),

    # ---------- 70 소통 ----------
    dict(
        id='AN-NOTI-010', name='알림', group='70_소통',
        file=WIRE, node='25:2', code='notification_screen.dart',
        summary='의뢰·제안·경매 마감·거래 단계·환불 등 도메인 이벤트 목록.',
        scenario='알림 탭에서 새 소식을 보고 항목을 누르면 관련 화면으로 바로 이동한다.',
        layout=['상단 바 + 모두 읽음', '알림 카드(종류 아이콘·제목·내용·경과 시간·미읽음 점)'],
        features=[
            'GET /api/notifications (100건 상한), 읽음 처리',
            '종류별 이동: 의뢰→의뢰 탭, 경매→작품 상세, 주문류→주문 내역, 채팅→채팅방',
            '푸시 알림 탭도 같은 규칙으로 이동(공용 유틸)',
        ],
        done=['탭하면 해당 화면으로 이동하고 미읽음 배지가 갱신된다'],
        notes=['푸시가 실제로 가는 알림은 사용자 지정 알림뿐 — 시스템 알림(userId 없음)은 앱 내에만 쌓인다'],
        deps='→ 각 상세 화면',
    ),
    dict(
        id='AN-CHAT-010', name='작품 문의 목록', group='70_소통',
        file=WIRE, node='26:2', code='chat_list_screen.dart',
        summary='작가와 나눈 1:1 대화 목록. 헤더 햄버거 서랍에서 진입한다.',
        scenario='서랍에서 작품 문의를 열면 대화 목록이 보이고, 상대 프로필과 마지막 메시지를 확인한 뒤 들어간다.',
        layout=['상단 바(작품 문의)', '대화 목록(상대 프로필·마지막 메시지·시간)'],
        features=['GET /api/chat/rooms/my (JWT 신원으로 상대 결정)'],
        done=['서버 데이터만 표시된다(오프라인 mock 없음)'],
        deps='← AN-ENT-060(서랍), → AN-CHAT-020',
    ),
    dict(
        id='AN-CHAT-020', name='채팅 상세', group='70_소통',
        file=WIRE, node='26:26', code='chat_screen.dart',
        summary='작가와 실시간으로 대화한다. 작품 상세·포트폴리오의 문의하기로도 진입한다.',
        scenario='문의하기를 누르면 대화방이 열린다. 메시지를 보내면 바로 상대에게 도착하고, 상대에게는 푸시 알림도 간다.',
        layout=['상단 바(상대 이름 · 실시간 연결됨)', '말풍선 목록', '입력창 + 전송'],
        features=[
            'POST /api/chat/rooms/direct {opponentNickname} — 있으면 재사용',
            'GET /api/chat/rooms/{roomId}/messages (참여자만, 200건 상한)',
            'STOMP 구독 /topic/chat/{roomId}, 전송 /app/chat/send',
            '새 메시지는 상대에게 알림 + 푸시',
        ],
        done=['보낸 메시지가 상대 화면에 즉시 표시되고 푸시가 도착한다'],
        notes=['보낸 메시지를 로컬에 먼저 추가하지 않는다 — 서버 에코 하나만 표시(중복 방지)'],
        deps='← AN-CHAT-010, AN-HOME-030, AN-HOME-040',
    ),

    # ---------- 80 마이 ----------
    dict(
        id='AN-MY-010', name='마이페이지', group='80_마이',
        file=WIRE, node='25:32', code='my_profile_screen.dart',
        summary='프로필과 역할, 그리고 소유권·관심·주문·거래·정산 메뉴의 허브.',
        scenario='마이페이지에서 내 정보를 확인하고, 소유권 인증서나 주문 내역 같은 기능으로 들어간다. 역할 배지를 눌러 작가↔컬렉터로 바꿀 수도 있다.',
        layout=['프로필 카드(사진·활동명·나이·역할 배지 ⇄)', '메뉴 리스트', '기본 정보 / 활동 지역 / 관심 장르'],
        features=[
            'GET /api/users/me',
            '역할 전환 PATCH /api/users/me {userType} — 확인 다이얼로그 후 즉시 반영',
            '메뉴: 소유권 인증서·디지털 소유권 / 관심 작품 / 주문 내역 / (작가) 내 작품 거래 / (작가) 판매 정산',
        ],
        done=['역할 전환 후에도 등록 작품·주문·소유권이 유지된다', '작가 전용 메뉴가 역할에 따라 노출된다'],
        notes=['userType 미전송 시 기존 역할 유지(부분 수정 원칙)'],
        deps='→ AN-OWN-010, AN-MY-020, AN-TRADE-020/030, AN-SELL-020',
    ),
    dict(
        id='AN-MY-020', name='관심 작품', group='80_마이',
        file=WIRE, node='28:2', code='liked_artworks_screen.dart',
        summary='하트를 누른 작품 모음.',
        scenario='마이페이지 > 관심 작품에서 담아둔 작품을 모아 보고 상세로 이동한다.',
        layout=['상단 바(관심 작품)', '작품 목록(썸네일·제목·작가·가격)'],
        features=['GET /api/artworks/liked', '판매 완료 건은 부제에 표시'],
        done=['하트 해제 시 목록에서 빠진다'],
        deps='← AN-MY-010, → AN-HOME-030',
    ),
]
