# -*- coding: utf-8 -*-
"""레퍼런스·보강 문서. tech_docs.DOCS 에 합쳐진다."""

EXTRA_DOCS = [
    dict(
        id='REF-010', group='8_레퍼런스', title='API 레퍼런스',
        summary='전체 엔드포인트 61개. 공개 여부와 신원 스코프를 함께 표기했다.',
        body=[
            ('c', '규칙: 조회(GET)만 공개, 나머지는 로그인 필수. 예외는 QR 스캔 하나. '
                  '"내 것" 목록은 JWT 신원으로 스코프한다.'),
            ('h', '인증 /auth (전부 공개)'),
            ('t', [
                ['메서드', '경로', '설명'],
                ['POST', '/auth/login', 'OAuth 토큰(KAKAO/NAVER)으로 앱 JWT 발급'],
                ['GET', '/auth/naver/config', '네이버 동의 화면 주소(시크릿 미포함)'],
                ['POST', '/auth/naver/code', '인가 코드 → 서버가 토큰 교환 후 JWT 발급'],
                ['POST', '/auth/refresh', 'refresh 회전 발급 + 폐기 기준선 검사'],
                ['POST', '/auth/logout', '발급된 토큰 전부 무효화(기준선 상승)'],
            ]),
            ('h', '작품 /api/artworks'),
            ('t', [
                ['메서드', '경로', '공개', '설명'],
                ['GET', '/api/artworks', '공개', '페이징 목록(size 1~50 클램프, 응답 키 content)'],
                ['GET', '/api/artworks/{id}', '공개', '상세(sold·reserved·wonByViewer 포함)'],
                ['GET', '/api/artworks/nearby', '공개', '주변 작품(latitude·longitude)'],
                ['GET', '/api/artworks/liked', '로그인', '내 관심 작품'],
                ['POST', '/api/artworks/{id}/like', '로그인', '하트 토글'],
                ['POST', '/api/artworks/{id}/bids', '로그인', '입찰(증분 미달 422)'],
                ['POST', '/api/artworks/{id}/close', '로그인', '경매 수동 마감'],
            ]),
            ('h', '거래 /api/orders'),
            ('t', [
                ['메서드', '경로', '설명'],
                ['POST', '/api/orders', '예약(결제 아님). 중복 409'],
                ['POST', '/api/orders/{id}/handover', '수령 확인(당사자만, 제3자 403)'],
                ['POST', '/api/orders/{id}/pay', '결제(구매자만, 양쪽 확인 후)'],
                ['POST', '/api/orders/{id}/cancel', '예약 취소'],
                ['GET', '/api/orders', '내 주문(구매자 스코프)'],
                ['GET', '/api/orders/selling', '내 작품 거래(판매자 스코프)'],
            ]),
            ('h', '소유권 · 판매 · 정산'),
            ('t', [
                ['메서드', '경로', '설명'],
                ['GET', '/api/certificates', '내 디지털 소유권(로그인, 환불분 제외)'],
                ['POST', '/api/certificates/scan', 'QR 조회 — 메서드 무관 공개(유일)'],
                ['POST', '/api/sales', '판매 등록(경매도 buyNowPrice 필수)'],
                ['GET', '/api/sales', '내 판매 작품(판매자 스코프)'],
                ['GET', '/api/settlements', '작가 정산(활동명 기준)'],
            ]),
            ('h', '의뢰 · 작가 · 리뷰'),
            ('t', [
                ['메서드', '경로', '설명'],
                ['POST · GET', '/api/commissions', '의뢰 등록 / 목록(공개)'],
                ['POST', '/api/commissions/{id}/offers', '작가 제안(최저가보다 낮아야 함)'],
                ['GET', '/api/artists/{활동명}', '작가 포트폴리오(공개)'],
                ['POST', '/api/artworks/{id}/reviews', '리뷰 작성(결제자만, 작품당 1회)'],
                ['GET', '/api/artists/{활동명}/reviews', '작가 리뷰 + 평균(공개)'],
            ]),
            ('h', '소통 · 기타'),
            ('t', [
                ['메서드', '경로', '설명'],
                ['GET', '/api/feed/home', '홈 피드(공개, 키: recommended/auctions/artists)'],
                ['POST', '/api/chat/rooms/direct', '1:1 방 열기(있으면 재사용)'],
                ['GET', '/api/chat/rooms/my', '내 대화 목록'],
                ['GET', '/api/chat/rooms/{id}/messages', '대화 내역(참여자만, 200건)'],
                ['GET', '/api/notifications', '알림 목록(100건)'],
                ['PATCH', '/api/notifications/{id}/read · /read-all', '읽음 처리'],
                ['POST · DELETE', '/api/devices', 'FCM 기기 등록 / 해제'],
                ['POST', '/api/images', '이미지 업로드 → /images/{파일명}'],
                ['GET', '/api/payments/config', '실 PG 사용 여부(공개)'],
                ['POST · GET · PATCH · DELETE', '/api/users · /api/users/me', '가입·조회·수정·탈퇴'],
            ]),
            ('h', '관리자 /api/admin (ROLE_ADMIN)'),
            ('t', [
                ['메서드', '경로', '설명'],
                ['POST', '/api/admin/login', '관리자 로그인(공개)'],
                ['PATCH', '/api/admin/password', '비밀번호 변경'],
                ['GET', '/api/admin/dashboard', '매출·회원·작품 지표'],
                ['GET', '/api/admin/members', '회원 검색'],
                ['POST', '/api/admin/members/{id}/block · unblock', '차단 / 해제'],
                ['GET', '/api/admin/orders', '주문 목록(직거래 단계 포함)'],
                ['POST', '/api/admin/orders/{id}/refund', '환불(결제 건만, 미결제는 400)'],
            ]),
            ('h', 'WebSocket'),
            ('t', [
                ['용도', '구독', '전송'],
                ['채팅', '/topic/chat/{roomId}', '/app/chat/send'],
                ['경매 현황', '/topic/auction/{artworkId}', '(서버 발행 전용)'],
            ]),
        ],
    ),
    dict(
        id='REF-020', group='8_레퍼런스', title='알림 · 이벤트',
        summary='알림 9종의 발생 시점 · 대상 · 푸시 여부 · 탭 시 이동.',
        body=[
            ('c', '푸시가 나가는 것은 publishTo(userId, …) 로 보낸 알림뿐이다. '
                  'publish(…) 는 userId=null 시스템 알림이라 대상이 없어 건너뛴다 — 푸시 테스트에 쓰면 안 된다.'),
            ('t', [
                ['종류', '언제', '대상', '푸시', '탭 시 이동'],
                ['COMMISSION_CREATED', '의뢰 등록', '해당 카테고리 작가(시스템)', '✕', '제작의뢰 탭'],
                ['COMMISSION_OFFER', '작가가 제안', '의뢰인(시스템)', '✕', '제작의뢰 탭'],
                ['AUCTION_CLOSED', '경매 마감', '낙찰자(시스템)', '✕', '작품 상세'],
                ['ORDER_RESERVED', '구매자가 예약', '판매자', '○', '주문 내역'],
                ['ORDER_HANDOVER', '상대가 수령 확인', '반대편 당사자', '○', '주문 내역'],
                ['ORDER_PAYMENT_DUE', '양쪽 확인 완료', '구매자', '○', '주문 내역'],
                ['ORDER_COMPLETED', '결제 완료', '구매자 + 판매자', '○', '주문 내역'],
                ['ORDER_CANCELLED', '예약 취소', '반대편 당사자', '○', '주문 내역'],
                ['ORDER_REFUNDED', '관리자 환불', '구매자', '○', '주문 내역'],
                ['CHAT_MESSAGE', '새 메시지', '상대방', '○', '해당 채팅방'],
            ]),
            ('h', '이동 규칙'),
            ('b', [
                '앱 내 알림 목록과 푸시 알림이 같은 규칙을 공유한다(utils/notification_navigation.dart)',
                '푸시는 화면 밖에서 눌리므로 BuildContext 가 없다 → MaterialApp 의 navigatorKey 로 이동',
                '앱이 죽어 있었으면 getInitialMessage, 백그라운드였으면 onMessageOpenedApp 으로 들어온다',
                '앱이 포그라운드면 안드로이드가 알림함에 띄우지 않는다(정상)',
            ]),
            ('c', '함정: 알림 종류를 추가했더니 저장이 500 으로 깨졌다. notifications.type 이 enum 목록 '
                  'CHECK 제약으로 굳어 있었고 ddl-auto=update 는 그 제약을 갱신하지 않는다. '
                  'columnDefinition = varchar(40) 으로 못박고, 기존 DB 는 EnumColumnConstraintFix 가 정리한다.'),
        ],
    ),
    dict(
        id='REF-030', group='8_레퍼런스', title='오류 코드',
        summary='도메인별 오류 코드와 HTTP 상태 — 클라이언트가 분기하는 근거.',
        body=[
            ('t', [
                ['코드', '상태', '의미'],
                ['COMMON_400_BODY', '400', '요청 본문을 해석할 수 없음'],
                ['COMMON_400_PARAM', '400', '쿼리 파라미터 누락·타입 오류'],
                ['COMMON_401', '401', '로그인 필요'],
                ['COMMON_404 / COMMON_405', '404 / 405', '없는 경로 / 허용되지 않은 메서드'],
                ['ORDER_409', '409', '이미 판매 완료된 작품'],
                ['ORDER_409_RESERVED', '409', '이미 예약된 작품'],
                ['ORDER_400_HANDOVER', '400', '양쪽 수령 확인 전 결제 시도'],
                ['ORDER_403_PARTICIPANT', '403', '거래 당사자가 아님'],
                ['ORDER_403_BUYER', '403', '구매자만 결제 가능'],
                ['ORDER_400_AUCTION', '400', '진행 중인 경매는 예약 불가'],
                ['ORDER_403_WINNER', '403', '낙찰자만 가능'],
                ['ORDER_409_REFUND', '409', '이미 환불된 주문'],
                ['USER_403_BLOCKED', '403', '차단된 계정'],
                ['AUTH_002 / AUTH_004', '401', 'OAuth 검증 실패 / refresh 무효'],
                ['CERTIFICATE_404 / CERTIFICATE_400', '404 / 400', '없는 QR 코드 / 빈 코드'],
                ['PAYMENT_422', '422', '토스 확정 금액과 주문 금액 불일치'],
                ['SALE_400_PRICE', '400', '판매가 누락(경매도 즉시 판매가 필수)'],
            ]),
            ('c', '함정 둘: ① 인증이 필요한 경로에 없는 하위 경로를 부르면 404 가 아니라 401 이 난다'
                  '(스프링 시큐리티가 먼저 막는다 — 경로 존재 여부를 노출하지 않는 정상 동작). '
                  '② 401 빈 본문이 보이면 인증이 아니라 서버 예외를 의심할 것(/error 디스패치 함정).'),
        ],
    ),
    dict(
        id='DOM-060', group='2_도메인', title='부가 기능 (리뷰 · 관심 · 페이징 · 역할 전환)',
        summary='본류는 아니지만 규칙이 있는 기능들.',
        body=[
            ('h', '리뷰'),
            ('b', [
                '자격: 그 작품을 결제까지 마쳤고 환불하지 않은 사람만',
                '작품당 1회(중복 409), 별점 1~5(벗어나면 400), 미구매자는 403',
                '포트폴리오 평점·리뷰 수는 실제 집계값(최신 100건 + 평균)',
                '환불하면 자격이 사라지고 앱에서 리뷰 버튼이 감춰진다',
            ]),
            ('h', '관심 작품(하트)'),
            ('b', [
                'POST /api/artworks/{id}/like 는 토글이다',
                '피드는 로그인 사용자의 하트 상태를 채워 내려준다',
                '하트는 판매 완료 딤 위에 올린다 — 팔린 뒤에도 담아둔 작품을 해제할 수 있어야 한다',
            ]),
            ('h', '페이징'),
            ('b', [
                '홈 피드는 섹션당 20건 상한 + 더보기',
                'GET /api/artworks?page=&size=&category= — size 는 1~50 으로 클램프',
                '응답은 Spring Page 라 목록 키가 content (피드의 recommended 와 다르다)',
                '알림 100건 · 대화 내역 200건 상한',
            ]),
            ('h', '역할 전환'),
            ('b', [
                '가입 후에도 작가 ↔ 컬렉터 전환 가능(마이페이지 역할 배지 ⇄)',
                'PATCH /api/users/me 는 userType 을 보내지 않으면 기존 역할을 유지한다(부분 수정 원칙)',
                '전환해도 등록 작품·주문·소유권은 그대로 — 역할은 화면 구성만 바꾼다',
            ]),
            ('h', '이미지'),
            ('b', [
                'POST /api/images multipart → /images/{파일명} 정적 서빙',
                '저장 위치는 app.upload-dir(기본 uploads/, gitignore)',
                '이미지·작품 정적 경로는 Cache-Control max-age 30일',
            ]),
        ],
    ),
    dict(
        id='ARCH-030', group='0_아키텍처', title='프론트엔드 구조',
        summary='Flutter 앱의 계층과 규칙(서비스 경유 · 토큰 사용 · i18n).',
        body=[
            ('h', '계층'),
            ('t', [
                ['폴더', '역할'],
                ['screens/', '라우트 단위 전체 화면 (25개)'],
                ['services/', 'REST·OAuth 클라이언트 — 화면에서 직접 HTTP 호출 금지'],
                ['models/', '응답 봉투 {code, message, data} 를 따르는 DTO'],
                ['widgets/', '공용 UI (SoldOverlay, AuctionCountdown, 워드마크)'],
                ['constants/', '디자인 토큰 · i18n 문자열 · API 베이스 URL'],
                ['providers/', 'ChangeNotifier (LocaleProvider)'],
                ['utils/', '이미지 URL 해석 · 알림 이동 규칙 · 금액 포매터'],
            ]),
            ('h', '규칙'),
            ('b', [
                '색·간격은 art_tokens.dart 토큰만 사용(하드코딩 금지)',
                'API 베이스 URL 은 api_config.dart 의 apiBaseUrl — 에뮬레이터는 10.0.2.2',
                '인증 헤더는 api_headers.dart 의 authJsonHeaders()/authOnlyHeaders() 로 통일',
                'JWT 는 AuthApiService 의 static 필드 + flutter_secure_storage 에 보관',
                '오프라인 mock 폴백은 제거됨 — 실패 시 빈 목록/null 을 돌려준다',
                '채팅은 보낸 메시지를 로컬에 먼저 추가하지 않는다(서버 에코 하나만 표시)',
            ]),
            ('h', 'i18n'),
            ('b', [
                'AppLanguage {ko, en, ja, zh} 4개국어',
                '문자열은 AppStrings 의 Map<AppLanguage,String>',
                '화면에서 context.watch<LocaleProvider>().tr(...) 로 렌더',
                '새 카피는 리터럴 인라인 대신 4개 로케일을 모두 채워 등록한다',
            ]),
            ('h', '네이티브 키'),
            ('b', [
                '카카오 키는 --dart-define 과 android/local.properties 양쪽에 같은 값이 필요하다',
                '지도 초기화 결과는 전역 isKakaoMapInitialized 로 노출 — 지도 화면은 이 플래그로 분기',
            ]),
        ],
    ),
    dict(
        id='ENV-040', group='6_개발환경', title='배포 · 운영 준비',
        summary='HTTPS 전환과 운영 전환 체크리스트.',
        body=[
            ('h', 'HTTPS'),
            ('b', [
                '앱: usesCleartextTraffic 대신 network_security_config.xml — 평문 HTTP 는 '
                '10.0.2.2 / localhost / 127.0.0.1 만 허용',
                '그래서 운영 주소에 실수로 http 를 써도 OS 가 차단한다',
                '백엔드: server.forward-headers-strategy=framework — TLS 는 리버스 프록시에서 끊는 전제',
                'X-Forwarded-* 를 신뢰해야 리다이렉트·절대 URL·쿠키 secure 판정이 https 기준으로 맞는다',
            ]),
            ('h', '운영 전환 체크리스트'),
            ('t', [
                ['항목', '할 일'],
                ['도메인·인증서', "Let's Encrypt 발급 → nginx 등 프록시 설정"],
                ['앱 빌드', '--dart-define=API_BASE_URL=https://...'],
                ['관리자 콘솔', 'artnara.apiBase 를 https 로(https 페이지에서 http 는 mixed content 로 막힌다)'],
                ['결제', 'TOSS_SECRET_KEY / TOSS_CLIENT_KEY 를 운영 키로 교체'],
                ['DB', 'MySQL 전환(DB_URL·DB_DRIVER·DB_USERNAME·DB_PASSWORD·DDL_AUTO)'],
                ['릴리스 서명', '릴리스 키스토어 지문을 카카오·네이버 콘솔에 등록'],
            ]),
            ('c', '릴리스(AOT) 빌드는 OneDrive 경로에서 app.dill 을 못 읽어 실패한다 — '
                  '필요하면 레포를 OneDrive 밖으로 복사해 빌드할 것.'),
        ],
    ),
]
